version: '3.8'

services:
  # FastAPI Backend
  edagent-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:///./edagent.db
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - YOUTUBE_API_KEY=${YOUTUBE_API_KEY}
      - SECRET_KEY=${SECRET_KEY:-your-secret-key-here}
      - ENVIRONMENT=development
    volumes:
      - ./edagent.db:/app/edagent.db
      - ./logs:/app/logs
    networks:
      - edagent-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Streamlit Frontend
  edagent-frontend:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    ports:
      - "8501:8501"
    environment:
      - EDAGENT_API_URL=http://edagent-api:8000/api/v1
      - EDAGENT_WS_URL=ws://edagent-api:8000/api/v1/ws
      - USE_MOCK_DATA=false
    depends_on:
      - edagent-api
    networks:
      - edagent-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501/_stcore/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Nginx Reverse Proxy (Optional)
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      - edagent-api
      - edagent-frontend
    networks:
      - edagent-network
    restart: unless-stopped

networks:
  edagent-network:
    driver: bridge

volumes:
  edagent-data:
    driver: local